apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-server-role-dataflow
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - pods/exec
    verbs:
      - deletecollection
  - apiGroups:
      - dataflow.argoproj.io
    resources:
      - pipelines
      - steps
    verbs:
      - get
      - list
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-server-binding-dataflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-server-role-dataflow
subjects:
- kind: ServiceAccount
  name: argo-server