apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: argo-dataflow-system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: ARGO_DATAFLOW_CLUSTER_NAME
          value: default
