apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-dataflow-system
resources:
- moto-init.task.yaml
- default.eventbus.yaml
- pipeline.yaml
- workflowtemplate.yaml

configMapGenerator:
- name: moto-init-script
  behavior: create
  files:
  - init-s3-bucket.sh=init-s3-bucket.sh
  options:
    disableNameSuffixHash: true
- name: s3-artifact-config
  behavior: create

  files:
  - default-v1=s3-artifact-config.yaml
  options:
    annotations:
      # v3.0 and after - if you want to use a specific key, put that's key into this annotation 
      workflows.argoproj.io/default-artifact-repository: default-v1
    disableNameSuffixHash: true