apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-dataflow-system
resources:
- moto-init.task.yaml
- default.eventbus.yaml
- pipeline.yaml
- workflowtemplate.yaml

configMapGenerator:
- name: moto-init-script
  behavior: create
  files:
  - init-s3-bucket.sh=init-s3-bucket.sh
  options:
    disableNameSuffixHash: true