apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-dataflow-system

resources:
  - github.com/argoproj/argo-workflows/manifests/namespace-install?ref=v3.1.9
  - workflow-role-binding.yaml

configMapGenerator:
- name: workflow-controller-configmap
  behavior: merge
  literals:
  - containerRuntimeExecutor=k8sapi
  options:
    disableNameSuffixHash: true

patchesStrategicMerge:
  - deployment-args.yaml

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: workflow-controller
    path: ./workflow-controller-deployment.yaml

images:
- name: docker.io/argoproj/argocli
  newName: quay.io/argoproj/argocli
  newTag: latest