apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-dataflow-system

resources:
  - github.com/argoproj/argo-events/manifests/namespace-install?ref=v1.4.1
  - operateworkflow.sa.yaml